import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "./components/theme-registry";
import { AppBar } from "@mui/material";
import SearchInput from "./features/stock/components/search-input";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <AppBar sx={{ padding: "1rem", marginBottom: "2rem" }} position="static">
            <SearchInput />
          </AppBar>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
